platform :ios, "7.0"

pod 'AFNetworking', '~> 3.1.0'
pod 'MJExtension', '~> 3.0.10'
pod 'LBBlurredImage', '~> 0.2.2'
pod 'Masonry', '1.0.1'
pod 'INTULocationManager', '~> 4.2.0'
pod 'MBProgressHUD', '~> 0.9.2'